services:
  web:
    build: .
    ports:
      - "8000:3000"
    environment:
      - DEFAULT_THEME=system
      - DEFAULT_LANGUAGE=fr
      - SETTINGS_SYNC_ENABLED=true
  redis:
    image: "redis:7-alpine"